# Generated by Django 4.2.7 on 2026-01-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('academic_year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
