# Generated by Django 4.2.7 on 2026-01-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=5)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('min_g_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_g_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(max_length=100)),
                ('teacher_remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
                ('full_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('has_practical', models.BooleanField(default=False)),
                ('theory_fm', models.IntegerField()),
                ('practical_fm', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtype')),
            ],
        ),
    ]
