# Generated by Django 4.2.7 on 2026-01-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_head', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('fee_type', models.CharField(choices=[('variable', 'Variable'), ('general', 'General'), ('occasionally', 'Occasionally')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
                ('month_name', models.CharField(max_length=20)),
                ('apply_dd_charges', models.CharField(choices=[('None', 'None'), ('Must', 'Must')], default='None', max_length=10)),
                ('general', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('twenty_five_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fifty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('out_of_three', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feehead')),
            ],
        ),
        migrations.CreateModel(
            name='FeeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('book_no', models.CharField(max_length=50)),
                ('order_no', models.CharField(max_length=50)),
                ('book_no_from', models.CharField(max_length=20)),
                ('book_no_to', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.financialyear')),
            ],
        ),
    ]
